/**
 * Authentication middleware verifying the request is signed by a known key.
 *
 * The middleware reads the Signature header, whose value should be the base64
 * representation of the signature generated by signing the request body with a
 * private key that matches one of the known public keys.
 *
 * If no matching key is found, 403 Forbidden is returned.
 */
import { warn } from 'console'
import crypto from 'crypto'
import { Request, Response, NextFunction, RequestHandler } from 'express'

const KNOWN_PUBLIC_KEYS: string[] = []

let _KEY_CACHE: crypto.KeyObject[] = []

/**
 * Load public key strings as `crypto.KeyObject`s, skipping keys we cannot load.
 *
 * Saves objects to a cache, for faster subsequent loading.
 */
function getKnownPublicKeys() {
  if (_KEY_CACHE.length === 0) {
    const keys: crypto.KeyObject[] = []
    for (let i = 0; i < KNOWN_PUBLIC_KEYS.length; i++) {
      try {
        const keyObject = crypto.createPublicKey({ key: KNOWN_PUBLIC_KEYS[i] })
        keys.push(keyObject)
      } catch (e) {
        console.warn(`signatureAuth: Could not load public key ${i} - check format`)
        continue
      }
    }
    _KEY_CACHE = keys
  }

  return _KEY_CACHE
}


/**
 * If a Signature header is present, treat this as service-based authentication;
 * if we cannot find a public key for which the signature is valid, return a 403.
 */
export function signatureAuthMiddleware(req: Request, res: Response, next: NextFunction) {
  // Check for a signature, which indicates service-based access
  const signature = req.header('Signature')
  if (signature) {
    const decodedSignature = Buffer.from(signature, 'base64')

    // Look for a public key for which the signature is valid
    let success = false
    for (const key of getKnownPublicKeys()) {
        if (crypto.verify(null, req.rawBody, key, decodedSignature)) {
          success = true
          break
        }
    }

    // Return 403 if invalid
    if (!success) {
      const msg = `Could not validate signature`
      console.log(msg)
      res.status(403).send(msg)
    }

    next()
    return
  }
}


// Populate cache
getKnownPublicKeys()
